=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountrecipientApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountrecipientApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountrecipientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountrecipientApi' do
    it 'should create an instance of AccountrecipientApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountrecipientApi)
    end
  end

  # unit tests for recipient_router_get_all_messages_for_a_recipient
  # Find all messages sent to a specific recipient
  # @param x_account_api_key Account API Key
  # @param recipient email of the recipient
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsQEmailMessage>]
  describe 'recipient_router_get_all_messages_for_a_recipient test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recipient_router_get_all_messages_for_a_recipient_from_a_node
  # Find all message sent to a recipient from a specific node
  # @param x_account_api_key Account API Key
  # @param recipient email of the recipient
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsQEmailMessage>]
  describe 'recipient_router_get_all_messages_for_a_recipient_from_a_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
