=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountsmtpstatApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountsmtpstatApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountsmtpstatApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsmtpstatApi' do
    it 'should create an instance of AccountsmtpstatApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountsmtpstatApi)
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_ip_provider_smtp_stats
  # Get All Aggregate IP Provider SMTP Stats
  # @param x_account_api_key Account API Key
  # @param ipid the IP ID you want to get
  # @param pname the provider name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_ip_provider_smtp_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_ip_smtp_stats
  # Get All Aggregate IP SMTP Stats
  # @param x_account_api_key Account API Key
  # @param ipid the IPId you want to get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_ip_smtp_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_ip_smtp_stats_for_sub_account
  # Get All Aggregate IP SMTP Stats For SubAccount
  # @param x_account_api_key Account API Key
  # @param ipid the IP ID you want to get
  # @param sid the SubAccount ID you want to get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_ip_smtp_stats_for_sub_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_sub_account_provider_smtp_stats
  # Get All Aggregate SubAccount Provider SMTP Stats
  # @param x_account_api_key Account API Key
  # @param sid the SubAccount ID you want to get
  # @param pname the provider name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_sub_account_provider_smtp_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_sub_account_smtp_stats
  # Get All Aggregate SubAccount SMTP Stats
  # @param x_account_api_key Account API Key
  # @param sid the Sub-Account ID you want to get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_sub_account_smtp_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for s_mtp_stat_router_get_all_aggregate_sub_account_smtp_stats_for_ip
  # Get All Aggregate SubAccount SMTP Stats For IP
  # @param x_account_api_key Account API Key
  # @param sid the Sub-Account ID you want to get
  # @param ipid the IP  ID you want to get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsSMTPStat>]
  describe 's_mtp_stat_router_get_all_aggregate_sub_account_smtp_stats_for_ip test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
