=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccounttagApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccounttagApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccounttagApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccounttagApi' do
    it 'should create an instance of AccounttagApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccounttagApi)
    end
  end

  # unit tests for tag_router_create
  # Create Tag
  # @param x_account_api_key Account API Key
  # @param body The Tag content
  # @param [Hash] opts the optional parameters
  # @return [ModelsTag]
  describe 'tag_router_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_router_delete
  # Delete Tag
  # @param x_account_api_key Account API Key
  # @param tagid The AccountTagId you want to delete
  # @param [Hash] opts the optional parameters
  # @return [ModelsDeleteResponse]
  describe 'tag_router_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_router_get_all
  # Get All Tags
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsTag>]
  describe 'tag_router_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
