=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountpaymentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountpaymentApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountpaymentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountpaymentApi' do
    it 'should create an instance of AccountpaymentApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountpaymentApi)
    end
  end

  # unit tests for payment_router_create_customer_portal
  # Create Customer Portal for account
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [ModelsBillingPortalSession]
  describe 'payment_router_create_customer_portal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_router_create_payment_subscription
  # Create Payment Subscription for Stripe
  # @param x_account_api_key Account API Key
  # @param body PaymentOptions content
  # @param [Hash] opts the optional parameters
  # @return [ModelsPaymentStatus]
  describe 'payment_router_create_payment_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payment_router_handle_payment_webhook
  # Handle Payment Related Webhooks
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payment_router_handle_payment_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
