=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountintegrationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountintegrationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountintegrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountintegrationApi' do
    it 'should create an instance of AccountintegrationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountintegrationApi)
    end
  end

  # unit tests for account_integration_router_count
  # Count Total AccountIntegrations
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [ModelsCountStat]
  describe 'account_integration_router_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_create
  # Create Integration
  # @param x_account_api_key Account API Key
  # @param itype The integration type you want to create
  # @param body The Integration content
  # @param [Hash] opts the optional parameters
  # @return [ModelsIntegration]
  describe 'account_integration_router_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_delete
  # Delete Integration
  # @param x_account_api_key Account API Key
  # @param itype The integration type you want to update
  # @param [Hash] opts the optional parameters
  # @return [ModelsDeleteResponse]
  describe 'account_integration_router_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_disable_glockapps_ip_monitoring
  # Disable IP Monitoring for a single IP
  # @param x_account_api_key Account API Key
  # @param ipid the IPId you want to disable monitoring for
  # @param [Hash] opts the optional parameters
  # @return [ModelsDeleteResponse]
  describe 'account_integration_router_disable_glockapps_ip_monitoring test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_enable_glockapps_ip_monitoring
  # Enable IP Monitoring for a single IP
  # @param x_account_api_key Account API Key
  # @param ipid the IPId you want to enable monitoring for
  # @param [Hash] opts the optional parameters
  # @return [ModelsResponse]
  describe 'account_integration_router_enable_glockapps_ip_monitoring test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_get_all
  # Get All Integrations
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsIntegration>]
  describe 'account_integration_router_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_get_monitored_ip_stats
  # Get Monitored IP Stats
  # @param x_account_api_key Account API Key
  # @param ipid the IPId for which you want monitored stats
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsRGlockappsMonitorStat>]
  describe 'account_integration_router_get_monitored_ip_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_integration_router_update
  # Update Integration
  # @param x_account_api_key Account API Key
  # @param itype The integration type you want to update
  # @param body The Integration content
  # @param [Hash] opts the optional parameters
  # @return [ModelsIntegration]
  describe 'account_integration_router_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
