=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountstatApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountstatApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountstatApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountstatApi' do
    it 'should create an instance of AccountstatApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountstatApi)
    end
  end

  # unit tests for account_stat_router_get_all_account_stats
  # Get All Account Stats
  # @param x_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsRStat>]
  describe 'account_stat_router_get_all_account_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_stat_router_get_all_account_stats_by_group
  # Get All Account Stats by Group
  # @param x_account_api_key Sub-Account API Key
  # @param group the group whose stats you want
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsRStat>]
  describe 'account_stat_router_get_all_account_stats_by_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_stat_router_get_all_aggregate_account_stats
  # Get All Aggregate Stats
  # @param x_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [ModelsStat]
  describe 'account_stat_router_get_all_aggregate_account_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_stat_router_get_all_aggregate_account_stats_by_group
  # Get All Aggregate Stats by Group
  # @param x_account_api_key Sub-Account API Key
  # @param group the group whose stats you want
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [ModelsStat]
  describe 'account_stat_router_get_all_aggregate_account_stats_by_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
