=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountonboardingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountonboardingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountonboardingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountonboardingApi' do
    it 'should create an instance of AccountonboardingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountonboardingApi)
    end
  end

  # unit tests for onboarding_router_get_onboarding_checklist
  # Gets Onboarding Checklist data for account if not present creates a default entry
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [ModelsOnboardingChecklist]
  describe 'onboarding_router_get_onboarding_checklist test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
