=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountmessageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountmessageApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountmessageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountmessageApi' do
    it 'should create an instance of AccountmessageApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountmessageApi)
    end
  end

  # unit tests for message_router_get
  # Find Message By Id
  # @param x_account_api_key Sub-Account API Key
  # @param message_id the messageId that you want to retrieve
  # @param [Hash] opts the optional parameters
  # @return [ModelsQEmailMessage]
  describe 'message_router_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for message_router_get_all_events_for_a_message_id
  # Find all events associated with a message id
  # @param x_account_api_key Account API Key
  # @param message_id the messageId that you want to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsQEvent>]
  describe 'message_router_get_all_events_for_a_message_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for message_router_get_all_events_for_a_message_id_from_a_node
  # Find all message events associated with a message id from a specific node
  # @param x_account_api_key Account API Key
  # @param message_id the messageId that you want to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsQEvent>]
  describe 'message_router_get_all_events_for_a_message_id_from_a_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for message_router_get_message_from_node
  # Find Message from node by specific Id
  # @param x_account_api_key Account API Key
  # @param message_id the messageId that you want to retrieve
  # @param [Hash] opts the optional parameters
  # @return [ModelsQEmailMessage]
  describe 'message_router_get_message_from_node test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
