=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountvalidateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountvalidateApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountvalidateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountvalidateApi' do
    it 'should create an instance of AccountvalidateApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountvalidateApi)
    end
  end

  # unit tests for validate_router_validate_email_bulk
  # Validate Emails In File Asynchronously
  # @param fileinput CSV whose emails need to be validated
  # @param x_account_api_key Account API Key
  # @param [Hash] opts the optional parameters
  # @return [ModelsBulkResponse]
  describe 'validate_router_validate_email_bulk test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for validate_router_validate_email_list
  # Validate Email List Synchronously
  # @param x_account_api_key Account API Key
  # @param body The email list to be sent for being validated
  # @param [Hash] opts the optional parameters
  # @return [ModelsCleanedList]
  describe 'validate_router_validate_email_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
