=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ClusterApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClusterApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ClusterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClusterApi' do
    it 'should create an instance of ClusterApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ClusterApi)
    end
  end

  # unit tests for cluster_router_delete_item_from_cache_of_every_node_in_cluster
  # Delete item from cache of every node in cluster
  # @param x_system_api_key System API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name cache name
  # @option opts [String] :key cache item key to delete
  # @return [nil]
  describe 'cluster_router_delete_item_from_cache_of_every_node_in_cluster test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cluster_router_delete_item_from_cache_of_specific_node_in_cluster
  # Delete item from cache of specific node in cluster
  # @param x_system_api_key System API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name cache name
  # @option opts [String] :key cache item key to delete
  # @return [nil]
  describe 'cluster_router_delete_item_from_cache_of_specific_node_in_cluster test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
