=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SubaccountemailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubaccountemailApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SubaccountemailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubaccountemailApi' do
    it 'should create an instance of SubaccountemailApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SubaccountemailApi)
    end
  end

  # unit tests for email_router_send_email
  # Send Email To Contacts
  # @param x_sub_account_api_key Sub-Account API Key
  # @param body The Email Message
  # @param [Hash] opts the optional parameters
  # @return [Array<ModelsEmailResponse>]
  describe 'email_router_send_email test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
