=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SubaccountstatApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubaccountstatApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SubaccountstatApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubaccountstatApi' do
    it 'should create an instance of SubaccountstatApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SubaccountstatApi)
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregate_sub_account_stats
  # Get All Aggregate Sub-Account Stats
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [ModelsStat]
  describe 'sub_account_stat_router_get_all_aggregate_sub_account_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group
  # Get All Aggregate Sub-Account Stats by Group
  # @param x_sub_account_api_key Sub-Account API Key
  # @param group the group whose stats you want
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [ModelsStat]
  describe 'sub_account_stat_router_get_all_aggregate_sub_account_stats_by_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account
  # Get All Aggregated Group Stats for a Sub-Account
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsAGStat>]
  describe 'sub_account_stat_router_get_all_aggregated_group_stats_for_a_sub_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account
  # Get All Aggregated IP Stats for a Sub-Account
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsAIPStat>]
  describe 'sub_account_stat_router_get_all_aggregated_ip_stats_for_a_sub_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account
  # Get All Aggregated Provider Stats for a Specific IP of a Sub-Account
  # @param x_sub_account_api_key Sub-Account API Key
  # @param ipid the IPId you want to get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsPIPStat>]
  describe 'sub_account_stat_router_get_all_aggregated_provider_stats_for_a_specific_ip_of_a_sub_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account
  # Get All Aggregated Provider Stats for a Sub-Account
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsPIPStat>]
  describe 'sub_account_stat_router_get_all_aggregated_provider_stats_for_a_sub_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_sub_account_stats
  # Get All Sub-Account Stats
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsRStat>]
  describe 'sub_account_stat_router_get_all_sub_account_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sub_account_stat_router_get_all_sub_account_stats_by_group
  # Get All Sub-Account Stats by Group
  # @param x_sub_account_api_key Sub-Account API Key
  # @param group the tag whose stats you want
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<ModelsRStat>]
  describe 'sub_account_stat_router_get_all_sub_account_stats_by_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
