=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SubaccountsenderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubaccountsenderApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SubaccountsenderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubaccountsenderApi' do
    it 'should create an instance of SubaccountsenderApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SubaccountsenderApi)
    end
  end

  # unit tests for sender_router_count
  # Count Total Senders
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @return [ModelsCountStat]
  describe 'sender_router_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sender_router_create
  # Create Sender
  # @param x_sub_account_api_key Sub-Account API Key
  # @param body The Sender content
  # @param [Hash] opts the optional parameters
  # @return [ModelsSender]
  describe 'sender_router_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sender_router_delete
  # Delete Sender
  # @param x_sub_account_api_key Sub-Account API Key
  # @param sender_id The SenderId you want to delete
  # @param [Hash] opts the optional parameters
  # @return [ModelsDeleteResponse]
  describe 'sender_router_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sender_router_get
  # Find Sender by SenderId
  # @param x_sub_account_api_key Sub-Account API Key
  # @param sender_id the SenderId you want to get
  # @param [Hash] opts the optional parameters
  # @return [ModelsSender]
  describe 'sender_router_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sender_router_get_all
  # Get All Senders
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset offset
  # @option opts [Integer] :limit limit
  # @option opts [String] :search search term
  # @return [Array<ModelsSender>]
  describe 'sender_router_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sender_router_update
  # Update Sender
  # @param x_sub_account_api_key Sub-Account API Key
  # @param sender_id The SenderId you want to update
  # @param body The body
  # @param [Hash] opts the optional parameters
  # @return [ModelsSender]
  describe 'sender_router_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
