=begin
#SendPost API

#Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.

The version of the OpenAPI document: 1.0.0
Contact: hello@sendpost.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Sendpost::SuppressionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SuppressionApi' do
  before do
    # run before each test
    @api_instance = Sendpost::SuppressionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SuppressionApi' do
    it 'should create an instance of SuppressionApi' do
      expect(@api_instance).to be_instance_of(Sendpost::SuppressionApi)
    end
  end

  # unit tests for count
  # Count Total Suppressions
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [CountStat]
  describe 'count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_suppressions
  # Add Email Addresses To Suppression List
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [RSuppression] :r_suppression Suppression content
  # @return [Array<Suppression>]
  describe 'create_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_suppression
  # Delete specific emails which are in suppression list
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [RDSuppression] :rd_suppression Suppression content
  # @return [Array<DeleteResponse>]
  describe 'delete_suppression test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_suppressions
  # Get all suppressions
  # @param x_sub_account_api_key Sub-Account API Key
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset offset
  # @option opts [Integer] :limit limit
  # @option opts [String] :search search
  # @option opts [String] :from from date
  # @option opts [String] :to to date
  # @return [Array<Suppression>]
  describe 'get_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
