=begin
#SendPost API

#SendPost API to send transactional emails reliably

OpenAPI spec version: 1.0.0
Contact: hello@sendx.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/_alert'
require 'swagger_client/models/models_ag_stat'
require 'swagger_client/models/models_aip_stat'
require 'swagger_client/models/models_account'
require 'swagger_client/models/models_account_ip_pool'
require 'swagger_client/models/models_account_template'
require 'swagger_client/models/models_account_webhook'
require 'swagger_client/models/models_alert_label'
require 'swagger_client/models/models_alert_request'
require 'swagger_client/models/models_alert_response'
require 'swagger_client/models/models_auth_info'
require 'swagger_client/models/models_back_off_configuration'
require 'swagger_client/models/models_back_off_decrease_type'
require 'swagger_client/models/models_back_off_trigger'
require 'swagger_client/models/models_billing_portal_session'
require 'swagger_client/models/models_blacklist_status'
require 'swagger_client/models/models_bulk_response'
require 'swagger_client/models/models_city'
require 'swagger_client/models/models_cleaned_list'
require 'swagger_client/models/models_comment'
require 'swagger_client/models/models_count_stat'
require 'swagger_client/models/models_customer_quality'
require 'swagger_client/models/models_dns_record'
require 'swagger_client/models/models_delete_response'
require 'swagger_client/models/models_detailed_alert'
require 'swagger_client/models/models_domain'
require 'swagger_client/models/models_e_account'
require 'swagger_client/models/models_e_account_member'
require 'swagger_client/models/models_e_comment'
require 'swagger_client/models/models_e_domain'
require 'swagger_client/models/models_eip'
require 'swagger_client/models/models_eip_pool'
require 'swagger_client/models/models_e_incident'
require 'swagger_client/models/models_e_integration'
require 'swagger_client/models/models_e_invitation'
require 'swagger_client/models/models_e_sender'
require 'swagger_client/models/models_e_sub_account'
require 'swagger_client/models/models_e_validation'
require 'swagger_client/models/models_e_webhook'
require 'swagger_client/models/models_editor_token_response'
require 'swagger_client/models/models_email_error_code'
require 'swagger_client/models/models_email_list'
require 'swagger_client/models/models_email_message'
require 'swagger_client/models/models_email_response'
require 'swagger_client/models/models_event_metadata'
require 'swagger_client/models/models_event_type'
require 'swagger_client/models/models_frequency_type'
require 'swagger_client/models/models_from'
require 'swagger_client/models/models_glockapps_blacklist'
require 'swagger_client/models/models_glockapps_monitor_stat'
require 'swagger_client/models/models_ieip'
require 'swagger_client/models/models_ie_member'
require 'swagger_client/models/models_ie_sub_account'
require 'swagger_client/models/models_ie_tag'
require 'swagger_client/models/models_iip'
require 'swagger_client/models/models_ip'
require 'swagger_client/models/models_ip_pool'
require 'swagger_client/models/models_ip_pool_type'
require 'swagger_client/models/models_ip_stat'
require 'swagger_client/models/models_ip_type'
require 'swagger_client/models/models_incident'
require 'swagger_client/models/models_incident_status'
require 'swagger_client/models/models_instance'
require 'swagger_client/models/models_integration'
require 'swagger_client/models/models_integration_settings'
require 'swagger_client/models/models_integration_type'
require 'swagger_client/models/models_invitation'
require 'swagger_client/models/models_invitation_status'
require 'swagger_client/models/models_label'
require 'swagger_client/models/models_member'
require 'swagger_client/models/models_member_role'
require 'swagger_client/models/models_notification_type'
require 'swagger_client/models/models_onboarding_checklist'
require 'swagger_client/models/models_pip_stat'
require 'swagger_client/models/models_payment_options'
require 'swagger_client/models/models_payment_status'
require 'swagger_client/models/models_q_email_message'
require 'swagger_client/models/models_q_event'
require 'swagger_client/models/models_rd_suppression'
require 'swagger_client/models/models_r_glockapps_monitor_stat'
require 'swagger_client/models/models_rip_stat'
require 'swagger_client/models/models_r_stat'
require 'swagger_client/models/models_r_suppression'
require 'swagger_client/models/models_reply_to'
require 'swagger_client/models/models_response'
require 'swagger_client/models/models_sip_stat'
require 'swagger_client/models/models_smtp_auth'
require 'swagger_client/models/models_smtp_stat'
require 'swagger_client/models/models_sender'
require 'swagger_client/models/models_single_cleaned_mail'
require 'swagger_client/models/models_stat'
require 'swagger_client/models/models_sub_account'
require 'swagger_client/models/models_sub_account_type'
require 'swagger_client/models/models_suppression'
require 'swagger_client/models/models_suppression_email'
require 'swagger_client/models/models_suppression_reason'
require 'swagger_client/models/models_system_dns_record'
require 'swagger_client/models/models_system_domain'
require 'swagger_client/models/models_system_ip_pool'
require 'swagger_client/models/models_system_template'
require 'swagger_client/models/models_tag'
require 'swagger_client/models/models_to'
require 'swagger_client/models/models_validation'
require 'swagger_client/models/models_validation_reason'
require 'swagger_client/models/models_verify_by_token_request'
require 'swagger_client/models/models_w_message'
require 'swagger_client/models/uaparser_device'
require 'swagger_client/models/uaparser_os'
require 'swagger_client/models/uaparser_user_agent'

# APIs
require 'swagger_client/api/accountevent_api'
require 'swagger_client/api/accountincident_api'
require 'swagger_client/api/accountintegration_api'
require 'swagger_client/api/accountip_api'
require 'swagger_client/api/accountippool_api'
require 'swagger_client/api/accountipstat_api'
require 'swagger_client/api/accountlabel_api'
require 'swagger_client/api/accountmember_api'
require 'swagger_client/api/accountmessage_api'
require 'swagger_client/api/accountonboarding_api'
require 'swagger_client/api/accountpayment_api'
require 'swagger_client/api/accountrecipient_api'
require 'swagger_client/api/accountsmtpstat_api'
require 'swagger_client/api/accountstat_api'
require 'swagger_client/api/accountsubaccount_api'
require 'swagger_client/api/accounttag_api'
require 'swagger_client/api/accounttemplate_api'
require 'swagger_client/api/accountvalidation_api'
require 'swagger_client/api/accountwebhook_api'
require 'swagger_client/api/cluster_api'
require 'swagger_client/api/editor_api'
require 'swagger_client/api/smtp_api'
require 'swagger_client/api/subaccountdomain_api'
require 'swagger_client/api/subaccountemail_api'
require 'swagger_client/api/subaccountippool_api'
require 'swagger_client/api/subaccountsender_api'
require 'swagger_client/api/subaccountstat_api'
require 'swagger_client/api/subaccountsuppression_api'
require 'swagger_client/api/system_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
