=begin
#SendPost API

#Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.

The version of the OpenAPI document: 1.0.0
Contact: hello@sendpost.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module Sendpost
  class QEmailMessage
    attr_accessor :account_id

    attr_accessor :amp_body

    attr_accessor :attachments

    attr_accessor :attempt

    attr_accessor :custom_fields

    attr_accessor :email_type

    attr_accessor :from

    attr_accessor :groups

    attr_accessor :header_bcc

    attr_accessor :header_cc

    attr_accessor :header_to

    attr_accessor :headers

    attr_accessor :html_body

    attr_accessor :ip_id

    attr_accessor :ip_pool

    attr_accessor :local_ip

    attr_accessor :message_id

    attr_accessor :pre_text

    attr_accessor :public_ip

    attr_accessor :reply_to

    attr_accessor :sub_account_id

    attr_accessor :subject

    attr_accessor :submitted_at

    attr_accessor :text_body

    attr_accessor :to

    attr_accessor :track_clicks

    attr_accessor :track_opens

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountID',
        :'amp_body' => :'ampBody',
        :'attachments' => :'attachments',
        :'attempt' => :'attempt',
        :'custom_fields' => :'customFields',
        :'email_type' => :'emailType',
        :'from' => :'from',
        :'groups' => :'groups',
        :'header_bcc' => :'headerBcc',
        :'header_cc' => :'headerCc',
        :'header_to' => :'headerTo',
        :'headers' => :'headers',
        :'html_body' => :'htmlBody',
        :'ip_id' => :'ipID',
        :'ip_pool' => :'ipPool',
        :'local_ip' => :'localIP',
        :'message_id' => :'messageID',
        :'pre_text' => :'preText',
        :'public_ip' => :'publicIP',
        :'reply_to' => :'replyTo',
        :'sub_account_id' => :'subAccountID',
        :'subject' => :'subject',
        :'submitted_at' => :'submittedAt',
        :'text_body' => :'textBody',
        :'to' => :'to',
        :'track_clicks' => :'trackClicks',
        :'track_opens' => :'trackOpens'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'Integer',
        :'amp_body' => :'String',
        :'attachments' => :'Array<Attachment>',
        :'attempt' => :'Integer',
        :'custom_fields' => :'Object',
        :'email_type' => :'String',
        :'from' => :'From',
        :'groups' => :'Array<String>',
        :'header_bcc' => :'Array<CopyTo>',
        :'header_cc' => :'Array<CopyTo>',
        :'header_to' => :'To',
        :'headers' => :'Object',
        :'html_body' => :'String',
        :'ip_id' => :'Integer',
        :'ip_pool' => :'String',
        :'local_ip' => :'String',
        :'message_id' => :'String',
        :'pre_text' => :'String',
        :'public_ip' => :'String',
        :'reply_to' => :'ReplyTo',
        :'sub_account_id' => :'Integer',
        :'subject' => :'String',
        :'submitted_at' => :'Integer',
        :'text_body' => :'String',
        :'to' => :'To',
        :'track_clicks' => :'Boolean',
        :'track_opens' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendpost::QEmailMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendpost::QEmailMessage`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'amp_body')
        self.amp_body = attributes[:'amp_body']
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'attempt')
        self.attempt = attributes[:'attempt']
      end

      if attributes.key?(:'custom_fields')
        self.custom_fields = attributes[:'custom_fields']
      end

      if attributes.key?(:'email_type')
        self.email_type = attributes[:'email_type']
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      end

      if attributes.key?(:'groups')
        if (value = attributes[:'groups']).is_a?(Array)
          self.groups = value
        end
      end

      if attributes.key?(:'header_bcc')
        if (value = attributes[:'header_bcc']).is_a?(Array)
          self.header_bcc = value
        end
      end

      if attributes.key?(:'header_cc')
        if (value = attributes[:'header_cc']).is_a?(Array)
          self.header_cc = value
        end
      end

      if attributes.key?(:'header_to')
        self.header_to = attributes[:'header_to']
      end

      if attributes.key?(:'headers')
        self.headers = attributes[:'headers']
      end

      if attributes.key?(:'html_body')
        self.html_body = attributes[:'html_body']
      end

      if attributes.key?(:'ip_id')
        self.ip_id = attributes[:'ip_id']
      end

      if attributes.key?(:'ip_pool')
        self.ip_pool = attributes[:'ip_pool']
      end

      if attributes.key?(:'local_ip')
        self.local_ip = attributes[:'local_ip']
      end

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      end

      if attributes.key?(:'pre_text')
        self.pre_text = attributes[:'pre_text']
      end

      if attributes.key?(:'public_ip')
        self.public_ip = attributes[:'public_ip']
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'sub_account_id')
        self.sub_account_id = attributes[:'sub_account_id']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'submitted_at')
        self.submitted_at = attributes[:'submitted_at']
      end

      if attributes.key?(:'text_body')
        self.text_body = attributes[:'text_body']
      end

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      end

      if attributes.key?(:'track_clicks')
        self.track_clicks = attributes[:'track_clicks']
      end

      if attributes.key?(:'track_opens')
        self.track_opens = attributes[:'track_opens']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          amp_body == o.amp_body &&
          attachments == o.attachments &&
          attempt == o.attempt &&
          custom_fields == o.custom_fields &&
          email_type == o.email_type &&
          from == o.from &&
          groups == o.groups &&
          header_bcc == o.header_bcc &&
          header_cc == o.header_cc &&
          header_to == o.header_to &&
          headers == o.headers &&
          html_body == o.html_body &&
          ip_id == o.ip_id &&
          ip_pool == o.ip_pool &&
          local_ip == o.local_ip &&
          message_id == o.message_id &&
          pre_text == o.pre_text &&
          public_ip == o.public_ip &&
          reply_to == o.reply_to &&
          sub_account_id == o.sub_account_id &&
          subject == o.subject &&
          submitted_at == o.submitted_at &&
          text_body == o.text_body &&
          to == o.to &&
          track_clicks == o.track_clicks &&
          track_opens == o.track_opens
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, amp_body, attachments, attempt, custom_fields, email_type, from, groups, header_bcc, header_cc, header_to, headers, html_body, ip_id, ip_pool, local_ip, message_id, pre_text, public_ip, reply_to, sub_account_id, subject, submitted_at, text_body, to, track_clicks, track_opens].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Sendpost.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
